setwd("~/GitHub/hspice/pwmADC/code")
input <- read.table("newcreation.txt", sep = "=", as.is = 4)
yval = as.numeric(input[, 4])
yval_log = log10(as.numeric(input[, 4]))
plot <- plot( input[, 2],yval_log, type = "b")
jpeg('linearity_log.png')
dev.off()

plot <- plot( input[, 2],yval, type = "b")
jpeg(file = "linearity.png")
dev.off()
#x11()