setwd("~/GitHub/hspice/pwmADC/code")
input <- read.table("newcreation.txt", sep = "=", as.is = 4)
yval = as.numeric(input[, 4])
yval_log = log10(as.numeric(input[, 4]))
jpeg('linearity_log.png')
plot <- plot( input[, 2],yval_log, type = "b")
dev.off()
jpeg(file = "linearity.png")
plot <- plot( input[, 2],yval, type = "b")
dev.off()
#x11()